version: '3'

services:
  openmeetings:
    container_name: openmeetings
    image: apache/openmeetings:min-7.2.0
    ports:
      - "5080:5080"
    networks:
      - macvlan-net
    volumes:
      - ./omdata:/opt/omdata
    environment:
      - OM_KURENTO_WS_URL=ws://kurento:8888/kurento
      - OM_DB_TYPE=postgresql
      - OM_DB_HOST=postgresql
      - OM_DB_PORT=5432
      - OM_DB_USER=openmeetings
      - OM_DB_PASS=openmeetings
      - OM_DB_NAME=openmeetings
    depends_on:
      - kurento
      - postgresql
    restart: always

  kurento:
    container_name: kurento
    image: kurento/kurento-media-server:6
    networks:
      - macvlan-net
    restart: always

  postgresql:
    container_name: postgresql
    image: postgres:15-alpine
    networks:
      - macvlan-net
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=openmeetings
      - POSTGRES_PASSWORD=openmeetings
      - POSTGRES_DB=openmeetings
    restart: always

networks:
  macvlan-net:
    driver: macvlan
    driver_opts:
      parent: wlp5s0
    ipam: 
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"